#!/bin/sh
# Mount common mountpoints like /proc

case "${1}" in
start)
    mkdir -p /proc
    mount -t proc proc /proc

    mkdir -p /dev
    mount -t devtmpfs devtmpfs /dev

    mkdir -p /sys
    mount -t sysfs sysfs /sys
    mount -t debugfs debugfs /sys/kernel/debug
    ;;

*)
    echo "Usage: ${0} start"
    exit 1
    ;;
esac

exit 0
